# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface_design.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 500)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 500))
        MainWindow.setMaximumSize(QtCore.QSize(800, 500))
        MainWindow.setBaseSize(QtCore.QSize(800, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("img/pinwheel.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.img = QtGui.QLabel(self.centralwidget)
        self.img.setGeometry(QtCore.QRect(0, 0, 500, 500))
        self.img.setStyleSheet(_fromUtf8("background: #000000"))
        self.img.setText(_fromUtf8(""))
        self.img.setScaledContents(False)
        self.img.setAlignment(QtCore.Qt.AlignCenter)
        self.img.setObjectName(_fromUtf8("img"))
        self.next_bt = QtGui.QPushButton(self.centralwidget)
        self.next_bt.setGeometry(QtCore.QRect(550, 450, 40, 34))
        self.next_bt.setObjectName(_fromUtf8("next_bt"))
        self.previous_bt = QtGui.QPushButton(self.centralwidget)
        self.previous_bt.setGeometry(QtCore.QRect(510, 450, 40, 34))
        self.previous_bt.setObjectName(_fromUtf8("previous_bt"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(510, 160, 281, 141))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.hue_label = QtGui.QLabel(self.groupBox)
        self.hue_label.setGeometry(QtCore.QRect(10, 30, 31, 20))
        self.hue_label.setObjectName(_fromUtf8("hue_label"))
        self.saturation_label = QtGui.QLabel(self.groupBox)
        self.saturation_label.setGeometry(QtCore.QRect(10, 70, 71, 20))
        self.saturation_label.setObjectName(_fromUtf8("saturation_label"))
        self.value_label = QtGui.QLabel(self.groupBox)
        self.value_label.setGeometry(QtCore.QRect(10, 110, 71, 20))
        self.value_label.setObjectName(_fromUtf8("value_label"))
        self.spin_h_min = QtGui.QSpinBox(self.groupBox)
        self.spin_h_min.setGeometry(QtCore.QRect(90, 20, 94, 36))
        self.spin_h_min.setMaximum(180)
        self.spin_h_min.setObjectName(_fromUtf8("spin_h_min"))
        self.spin_s_min = QtGui.QSpinBox(self.groupBox)
        self.spin_s_min.setGeometry(QtCore.QRect(90, 60, 94, 36))
        self.spin_s_min.setMaximum(255)
        self.spin_s_min.setObjectName(_fromUtf8("spin_s_min"))
        self.spin_v_min = QtGui.QSpinBox(self.groupBox)
        self.spin_v_min.setGeometry(QtCore.QRect(90, 100, 94, 36))
        self.spin_v_min.setMaximum(255)
        self.spin_v_min.setObjectName(_fromUtf8("spin_v_min"))
        self.spin_h_max = QtGui.QSpinBox(self.groupBox)
        self.spin_h_max.setGeometry(QtCore.QRect(188, 20, 94, 36))
        self.spin_h_max.setMaximum(180)
        self.spin_h_max.setProperty("value", 180)
        self.spin_h_max.setObjectName(_fromUtf8("spin_h_max"))
        self.spin_s_max = QtGui.QSpinBox(self.groupBox)
        self.spin_s_max.setGeometry(QtCore.QRect(188, 60, 94, 36))
        self.spin_s_max.setMaximum(255)
        self.spin_s_max.setProperty("value", 255)
        self.spin_s_max.setObjectName(_fromUtf8("spin_s_max"))
        self.spin_v_max = QtGui.QSpinBox(self.groupBox)
        self.spin_v_max.setGeometry(QtCore.QRect(188, 100, 94, 36))
        self.spin_v_max.setMaximum(255)
        self.spin_v_max.setProperty("value", 255)
        self.spin_v_max.setObjectName(_fromUtf8("spin_v_max"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(510, 10, 281, 141))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.hue_label_2 = QtGui.QLabel(self.groupBox_2)
        self.hue_label_2.setGeometry(QtCore.QRect(10, 30, 41, 20))
        self.hue_label_2.setObjectName(_fromUtf8("hue_label_2"))
        self.saturation_label_2 = QtGui.QLabel(self.groupBox_2)
        self.saturation_label_2.setGeometry(QtCore.QRect(10, 70, 71, 20))
        self.saturation_label_2.setObjectName(_fromUtf8("saturation_label_2"))
        self.file_text = QtGui.QLineEdit(self.groupBox_2)
        self.file_text.setGeometry(QtCore.QRect(90, 60, 191, 36))
        self.file_text.setReadOnly(True)
        self.file_text.setObjectName(_fromUtf8("file_text"))
        self.hue_label_3 = QtGui.QLabel(self.groupBox_2)
        self.hue_label_3.setGeometry(QtCore.QRect(10, 110, 81, 20))
        self.hue_label_3.setObjectName(_fromUtf8("hue_label_3"))
        self.size_h = QtGui.QSpinBox(self.groupBox_2)
        self.size_h.setGeometry(QtCore.QRect(188, 100, 94, 36))
        self.size_h.setMaximum(999999999)
        self.size_h.setObjectName(_fromUtf8("size_h"))
        self.size_w = QtGui.QSpinBox(self.groupBox_2)
        self.size_w.setGeometry(QtCore.QRect(90, 100, 94, 36))
        self.size_w.setMaximum(999999999)
        self.size_w.setObjectName(_fromUtf8("size_w"))
        self.path_text = QtGui.QLineEdit(self.groupBox_2)
        self.path_text.setGeometry(QtCore.QRect(90, 20, 151, 36))
        self.path_text.setReadOnly(False)
        self.path_text.setObjectName(_fromUtf8("path_text"))
        self.path_button = QtGui.QPushButton(self.groupBox_2)
        self.path_button.setGeometry(QtCore.QRect(240, 20, 41, 36))
        self.path_button.setObjectName(_fromUtf8("path_button"))
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(510, 310, 281, 121))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.keep_size = QtGui.QCheckBox(self.groupBox_3)
        self.keep_size.setGeometry(QtCore.QRect(10, 30, 161, 25))
        self.keep_size.setObjectName(_fromUtf8("keep_size"))
        self.morphological_operations = QtGui.QCheckBox(self.groupBox_3)
        self.morphological_operations.setGeometry(QtCore.QRect(10, 76, 201, 25))
        self.morphological_operations.setObjectName(_fromUtf8("morphological_operations"))
        self.blur = QtGui.QCheckBox(self.groupBox_3)
        self.blur.setGeometry(QtCore.QRect(10, 100, 61, 25))
        self.blur.setObjectName(_fromUtf8("blur"))
        self.fit_screen = QtGui.QCheckBox(self.groupBox_3)
        self.fit_screen.setGeometry(QtCore.QRect(10, 53, 131, 25))
        self.fit_screen.setObjectName(_fromUtf8("fit_screen"))
        self.save_bt = QtGui.QPushButton(self.centralwidget)
        self.save_bt.setGeometry(QtCore.QRect(710, 450, 85, 34))
        self.save_bt.setObjectName(_fromUtf8("save_bt"))
        self.apply_bt = QtGui.QPushButton(self.centralwidget)
        self.apply_bt.setGeometry(QtCore.QRect(635, 450, 71, 34))
        self.apply_bt.setObjectName(_fromUtf8("apply_bt"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(2, 483, 131, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Sans Fallback"))
        font.setPointSize(7)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Wava Image Dataset Processing - WADP", None))
        self.next_bt.setText(_translate("MainWindow", ">", None))
        self.previous_bt.setText(_translate("MainWindow", "<", None))
        self.groupBox.setTitle(_translate("MainWindow", "HSV Settings", None))
        self.hue_label.setText(_translate("MainWindow", "Hue:", None))
        self.saturation_label.setText(_translate("MainWindow", "Saturation:", None))
        self.value_label.setText(_translate("MainWindow", "Value:", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Content Info", None))
        self.hue_label_2.setText(_translate("MainWindow", "Path:", None))
        self.saturation_label_2.setText(_translate("MainWindow", "File name:", None))
        self.hue_label_3.setText(_translate("MainWindow", "Size:", None))
        self.path_button.setText(_translate("MainWindow", "...", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Options", None))
        self.keep_size.setText(_translate("MainWindow", "Non-original size", None))
        self.morphological_operations.setText(_translate("MainWindow", "Morphological Operations", None))
        self.blur.setText(_translate("MainWindow", "Blur", None))
        self.fit_screen.setText(_translate("MainWindow", "Fit screen", None))
        self.save_bt.setText(_translate("MainWindow", "Save", None))
        self.apply_bt.setText(_translate("MainWindow", "Apply", None))
        self.label.setText(_translate("MainWindow", "Copyright © 2017 Allex Lima", None))

